"use client";

import { Activity, Pencil, Power, Trash2 } from "lucide-react";
import type { WebhookSubscription } from "@/lib/api/webhooks";

interface Props { subscriptions: WebhookSubscription[]; onEdit: (subscription: WebhookSubscription) => void; onToggle: (subscription: WebhookSubscription) => void; onDelete: (subscription: WebhookSubscription) => void; onDeliveries: (subscription: WebhookSubscription) => void; }

export function WebhookTable({ subscriptions, onEdit, onToggle, onDelete, onDeliveries }: Props) {
  return <div className="overflow-x-auto rounded-2xl border border-white/10 bg-white/[0.03]"><table className="w-full text-left text-sm"><thead className="border-b border-white/10 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Endpoint</th><th className="px-5 py-4">Events</th><th className="px-5 py-4">Created</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-white/10">{subscriptions.map((subscription) => <tr key={subscription.id} className="text-slate-300"><td className="max-w-xs px-5 py-4"><div className="truncate font-mono text-xs">{subscription.targetUrl}</div><div className="mt-1 text-xs text-slate-500">{subscription.id}</div></td><td className="px-5 py-4"><div className="flex max-w-sm flex-wrap gap-1">{subscription.eventTypes.map((event) => <span key={event} className="rounded bg-white/10 px-2 py-1 text-[10px]">{event}</span>)}</div></td><td className="whitespace-nowrap px-5 py-4 text-slate-400">{new Date(subscription.createdAt).toLocaleDateString()}</td><td className="px-5 py-4"><span className={`rounded-full px-2 py-1 text-xs ${subscription.isActive ? "bg-emerald-400/15 text-emerald-300" : "bg-slate-400/15 text-slate-400"}`}>{subscription.isActive ? "Active" : "Inactive"}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button onClick={() => onDeliveries(subscription)} aria-label="View delivery logs" title="View delivery logs"><Activity size={16} /></button><button onClick={() => onEdit(subscription)} aria-label="Edit webhook" title="Edit webhook"><Pencil size={16} /></button><button onClick={() => onToggle(subscription)} aria-label="Toggle webhook" title="Toggle webhook"><Power size={16} /></button><button onClick={() => onDelete(subscription)} aria-label="Delete webhook" title="Delete webhook" className="text-rose-400"><Trash2 size={16} /></button></div></td></tr>)}</tbody></table>{subscriptions.length === 0 && <p className="p-10 text-center text-sm text-slate-400">No webhook endpoints registered yet.</p>}</div>;
}