"use client";

import { useEffect, useState } from "react";
import { ChevronDown, ChevronRight, X } from "lucide-react";
import { listWebhookDeliveries, sendWebhookTest, type WebhookDelivery, type WebhookSubscription } from "@/lib/api/webhooks";
import toast from "react-hot-toast";

export function WebhookDeliveryModal({ subscription, userAddress, onClose }: { subscription: WebhookSubscription; userAddress: string; onClose: () => void }) {
  const [deliveries, setDeliveries] = useState<WebhookDelivery[]>([]); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [expanded, setExpanded] = useState<string | null>(null); const [testing, setTesting] = useState(false);
  useEffect(() => { void listWebhookDeliveries(subscription.id, userAddress, page).then((result) => { setDeliveries(result.deliveries); setTotal(result.total); }).catch((error: unknown) => toast.error(error instanceof Error ? error.message : "Failed to load delivery logs")); }, [subscription.id, userAddress, page]);
  const test = async () => { setTesting(true); try { const result = await sendWebhookTest(subscription.id, userAddress); result.success ? toast.success(`Test delivered (${result.status ?? "2xx"})`) : toast.error(result.error ?? `Receiver returned ${result.status ?? 0}`); } catch (error) { toast.error(error instanceof Error ? error.message : "Test failed"); } finally { setTesting(false); } };
  return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/70 p-4" role="dialog" aria-modal="true"><div className="max-h-[85vh] w-full max-w-5xl overflow-auto rounded-2xl border border-white/10 bg-slate-950 p-6 text-white"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Delivery logs</h2><p className="mt-1 truncate text-xs text-slate-400">{subscription.targetUrl}</p></div><div className="flex items-center gap-3"><button onClick={() => void test()} disabled={testing} className="rounded-lg bg-emerald-400 px-3 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50">{testing ? "Sending..." : "Send test event"}</button><button onClick={onClose} aria-label="Close"><X /></button></div></div><table className="mt-6 w-full text-left text-sm"><thead className="border-b border-white/10 text-xs text-slate-500"><tr><th className="px-3 py-3">Time</th><th className="px-3 py-3">Event</th><th className="px-3 py-3">HTTP</th><th className="px-3 py-3">Attempts</th><th className="px-3 py-3">Payload</th></tr></thead><tbody className="divide-y divide-white/10">{deliveries.map((delivery) => <tr key={delivery.id} className="align-top"><td className="px-3 py-3 text-xs text-slate-400">{new Date(delivery.createdAt).toLocaleString()}</td><td className="px-3 py-3">{delivery.eventType}</td><td className={`px-3 py-3 font-semibold ${delivery.responseStatus && delivery.responseStatus < 300 ? "text-emerald-300" : "text-rose-300"}`}>{delivery.responseStatus ?? "ERR"}</td><td className="px-3 py-3">{delivery.attempts}</td><td className="px-3 py-3"><button onClick={() => setExpanded(expanded === delivery.id ? null : delivery.id)} aria-label={`Expand payload ${delivery.id}`}>{expanded === delivery.id ? <ChevronDown size={16} /> : <ChevronRight size={16} />}</button>{expanded === delivery.id && <pre className="mt-2 max-w-xl overflow-auto rounded bg-black/40 p-3 text-xs text-slate-300">{delivery.payload}</pre>}</td></tr>)}</tbody></table><div className="mt-5 flex justify-between text-sm text-slate-400"><span>{total} deliveries</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)} className="rounded border border-white/10 px-3 py-1 disabled:opacity-40">Previous</button><button disabled={page * 20 >= total} onClick={() => setPage((value) => value + 1)} className="rounded border border-white/10 px-3 py-1 disabled:opacity-40">Next</button></div></div></div></div>;
}