"use client";

import { useMemo, useState } from "react";
import { estimateRunwayDate, getCliffDates, projectCashflow, type ProjectionStream } from "@/utils/cashflowCalculations";

const horizons = [7, 30, 90, 180, 365] as const;
export function CashflowProjectionChart({ streams }: { streams: ProjectionStream[] }) {
  const [horizon, setHorizon] = useState<number>(30); const [currency, setCurrency] = useState<"token" | "fiat">("token"); const [hovered, setHovered] = useState<number | null>(null);
  const points = useMemo(() => projectCashflow(streams, horizon), [streams, horizon]); const runway = useMemo(() => estimateRunwayDate(streams), [streams]); const cliffs = useMemo(() => getCliffDates(streams), [streams]); const max = Math.max(1, ...points.map((point) => Math.max(point.projected, point.actual)));
  const path = points.map((point, index) => `${(index / Math.max(1, points.length - 1)) * 100},${100 - (point.projected / max) * 90}`).join(" L "); const area = `M 0,100 L ${path} L 100,100 Z`;
  return <section className="dashboard-panel mt-8"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h3>Cashflow projection</h3><p className="text-sm text-slate-400">Actual accrual and projected balance</p></div><div className="flex gap-1">{horizons.map((value) => <button key={value} onClick={() => setHorizon(value)} className={`rounded px-2 py-1 text-xs ${horizon === value ? "bg-accent/20 text-accent" : "text-slate-400"}`}>{value === 365 ? "1Y" : `${value}D`}</button>)}<button onClick={() => setCurrency(currency === "token" ? "fiat" : "token")} className="ml-2 rounded border border-white/10 px-2 py-1 text-xs">{currency === "token" ? "Token" : "USD"}</button></div></div><div className="relative mt-6 h-64 rounded-xl bg-slate-950/40 p-4"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-full w-full" onMouseMove={(event) => setHovered(Math.round((event.nativeEvent.offsetX / event.currentTarget.clientWidth) * (points.length - 1)))}><path d={area} fill="currentColor" className="text-emerald-400/10" /><path d={`M ${path}`} fill="none" stroke="currentColor" strokeWidth="0.8" className="text-emerald-300" />{runway && <line x1={`${Math.min(100, Math.max(0, ((runway.getTime() - points[0]!.date.getTime()) / (points[points.length - 1]!.date.getTime() - points[0]!.date.getTime())) * 100))}`} x2={`${Math.min(100, Math.max(0, ((runway.getTime() - points[0]!.date.getTime()) / (points[points.length - 1]!.date.getTime() - points[0]!.date.getTime())) * 100))}`} y1="0" y2="100" stroke="#fb7185" strokeDasharray="3 2" />}{cliffs.map((cliff) => <line key={cliff.toISOString()} x1={`${Math.min(100, Math.max(0, ((cliff.getTime() - points[0]!.date.getTime()) / (points[points.length - 1]!.date.getTime() - points[0]!.date.getTime())) * 100))}`} x2={`${Math.min(100, Math.max(0, ((cliff.getTime() - points[0]!.date.getTime()) / (points[points.length - 1]!.date.getTime() - points[0]!.date.getTime())) * 100))}`} y1="0" y2="100" stroke="#4ade80" />)}</svg>{hovered !== null && points[hovered] && <div className="absolute right-4 top-4 rounded bg-slate-900/90 px-3 py-2 text-xs text-slate-200">{points[hovered].date.toLocaleDateString()}<br />Rate: {points[hovered].dailyRate.toFixed(4)}<br />Balance: {points[hovered].balance.toFixed(4)} {currency === "token" ? "tokens" : "USD"}</div>}</div><div className="mt-3 flex gap-5 text-xs text-slate-400"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-rose-400" />Runway {runway ? runway.toLocaleDateString() : "not estimated"}</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-green-400" />Cliff unlocks</span></div></section>;
}